Repository chingu-voyages/soloproject-evaluation, pull requests merged in 2023-10, with the labels that each got.

#9 Feature: Add advice for CSS embedded in HTML
  README.md
Labels: documentation

#8 Add github actions to trigger firebase functions
  .github/workflows/update.yml
Labels: enhancement

#10 Add additional feedback for Data Science Solo Projects
  .github/workflows/update.yml
  README.md
Labels: documentation, enhancement

#11 Add Data Science feedback
  README.md
Labels: documentation, enhancement
